# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Print the current date
  - trigger: ":dt"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: ":tod"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d %A"
  - trigger: ":e1"
    replace: "comrade.topanga@gmail.com"
  - trigger: ":e2"
    replace: "zachary.levine89@gmail.com"
  - trigger: ":e3"
    replace: "zach@zjlevine.dev"
  - trigger: ":e4"
    replace: "zachary.levine@onedigital.com"
  - trigger: ":fn"
    form: "[^[[index]]]: "
  - trigger: "bw"
    replace: "between"
  - trigger: "Bw"
    replace: "Between"
  - trigger: "btw"
    replace: "by the way"
  - trigger: "Btw"
    replace: "By the way"
  # - trigger: "nvm"
  #   replace: "never mind"
  - trigger: "Nvm"
    replace: "Never mind"
  - trigger: "tbf"
    replace: "to be fair"
  - trigger: "Tbf"
    replace: "To be fair"
  - trigger: "gthr"
    replace: "go through"
  - trigger: "tbh"
    replace: "to be honest"
  - trigger: "Tbh"
    replace: "To be honest"
  - trigger: "wrt"
    replace: "with regard to"
  - trigger: "Wrt"
    replace: "With regard to"
  - trigger: "afaict"
    replace: "as far as I can tell"
  - trigger: "Afaict"
    replace: "As far as I can tell"
  - trigger: "iirc"
    replace: "if I remember correctly"
  - trigger: "Iirc"
    replace: "If I remember correctly"
  - trigger: ":sig"
    replace: >
      Thank you,
        --Zachary Levine

# And much more! For more information, visit the docs: https://espanso.org/docs/
