#!/usr/bin/env zsh

# Completion helpers for Python tools
# Wraps python-utils.zsh functions with completion formatting

# Complete with pyenv versions
_comp_pyenv_versions() {
  autoload -Uz getPyenvVersions
  
  local -a versions
  
  while IFS= read -r version; do
    [[ -n "$version" ]] && versions+=("$version")
  done < <(getPyenvVersions)
  
  if (( ${#versions[@]} > 0 )); then
    _describe 'pyenv versions' versions
    return 0
  fi
  return 1
}
