alias_path="$ZSH_CONFIG_DIR/aliases"

source "$alias_path/dash-g.zsh"
source "$alias_path/dates.zsh"
source "$alias_path/db.zsh"
source "$alias_path/docker.zsh"
source "$alias_path/git.zsh"
source "$alias_path/golang.zsh"
source "$alias_path/js-ts.zsh"
source "$alias_path/kubernetes.zsh"
source "$alias_path/lua.zsh"
source "$alias_path/misc.zsh"
source "$alias_path/nvim.zsh"
source "$alias_path/python.zsh"
source "$alias_path/searching.zsh"
source "$alias_path/slack.zsh"
source "$alias_path/tui-tools.zsh"
source "$alias_path/todo-tools.zsh"
source "$alias_path/utils.zsh"
source "$alias_path/wezterm.zsh"
source "$alias_path/work/index.zsh"
