#!/bin/sh
set -eu
PATH="/usr/local/bin:$PATH"

TMP_TAGS="$(mktemp tags.XXXXXX)"
cleanup() {
  rm -f "$TMP_TAGS"
}
trap cleanup EXIT

git ls-files -z |
  ctags --tag-relative=yes \
    --fields=+l \
    --sort=yes \
    --extras=+q \
    -L - \
    -f "$TMP_TAGS" \
    --excmd=number

mv "$TMP_TAGS" tags
