return {
  { "sunaku/vim-dasht", event = "VeryLazy" },
  {
    "luckasRanarison/nvim-devdocs",
    event = "VeryLazy",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim",
      "nvim-treesitter/nvim-treesitter",
    },
    opts = {
      ensure_installed = {
        "angular",
        "angular-16",
        "axios",
        "bash",
        "css",
        "date_fns",
        "docker",
        "eslint",
        "fastapi",
        "git",
        "html",
        "http",
        "i3",
        "javascript",
        "jest",
        "jq",
        "lua-5.1",
        "markdown",
        "nextjs",
        "node",
        "node-20_lts",
        "npm",
        "playwright",
        "prettier",
        "python-3.12",
        "ramda",
        "react",
        "rxjs",
        "tailwindcss",
        "typescript",
      },
      filetypes = {
        scss = { "sass", "css", "tailwindcss" },
        javascript = { "node", "javascript", "tailwindcss" },
        typescript = { "node", "javascript", "typescript", "tailwindcss" },
        javascriptreact = { "node", "javascript", "react", "tailwindcss" },
        typescriptreact = { "node", "javascript", "typescript", "react", "tailwindcss" },
        css = { "tailwindcss", "css" },
      },
      previewer_cmd = "glow",
    },
  },
}
